sudo: false
language: node_js
node_js:
  - "8.10"
  - "10.0"
  - "node"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  hosts:
    - nic.localhost
    - tim.localhost
    - nicola.localhost
script:
  - snyk test
  - npm run standard
  - npm run sonar
  - npm run nyc
cache:
  apt: true
  directories:
    - node_modules
notifications:
  email:
  - solid@janeirodigital.com
  - solid-travis@inrupt.com
  